pipeline {
  agent { 
    docker {
      image "maven:3.9-eclipse-temurin-21" 
      args '-u root'
    }
  }


  stages {
    
    stage('maven') {
      steps {
        sh "mvn -version"
        sh "java -version"
        sh "ls -alh;pwd"
        sh "printenv"
      }
    }
    
    stage('build') {
      steps {
        sh "mvn clean install"
      }
    }
  }

  post {
    always {
      junit skipMarkingBuildUnstable: true, stdioRetention: '', testResults: '**/**/target/surefire-reports/TEST*.xml'
      emailext body: 'Result: ${currentBuild.currentResult} Build # ${BUILD_NUMBER}', recipientProviders: [buildUser()], subject: 'Build # ${BUILD_NUMBER} status Your build ${currentBuild.displayName} failed.'
    }
  }

}
