pipeline {
  agent { 
    docker {
      image "maven:3.9-eclipse-temurin-21" 
      args '-u root'
    }
  }


  stages {
    
    stage('maven') {
      steps {
        sh "mvn -version"
        sh "java -version"
        sh "ls -alh;pwd"
        sh "printenv"
      }
    }
    
    stage('build') {
      steps {
        sh "mvn clean install"
      }
    }

    stage("capture") {
      steps {
        junit skipMarkingBuildUnstable: true, '**/**/target/surefire-reports/TEST*.xml'    
      }  
  
  }
  }

}
